# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('book_year', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('voting_closed', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('image', models.FilePathField(default='/images/book-default.png')),
            ],
        ),
    ]
