# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
