# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20160418_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
