# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20160426_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
