# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20160502_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
