# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0023_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='votes',
        ),
        migrations.AddField(
            model_name='book',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
